site_name: OpenAI Agents SDK
site_url: https://yusuf-eren.github.io/openai-agents-js/
theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
    - navigation.path
    - navigation.sections
    - navigation.expand
    - content.code.annotate
  palette:
    primary: black
  logo: assets/logo.svg
  favicon: images/favicon-platform.svg

repo_name: openai-agents-js
repo_url: https://github.com/yusuf-eren/openai-agents-js

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/agents"]
          selection:
            docstring_style: google
          options:
            signature_crossrefs: true
            members_order: source
            separate_signature: true
            show_signature_annotations: true
            heading_level: 3
            inherited_members: true
  - i18n:
      default_language: en
      docs_structure: folder
      languages:
          default: true
          name: English
          build: true
          nav:
            - Intro: index.md
            - Quickstart: quickstart.md
            # Coming soon:
            # - Examples: examples.md
            # - Documentation:
            #     - agents.md
            #     - running_agents.md
            #     - results.md
            #     - streaming.md
            #     - tools.md
            #     - mcp.md
            #     - handoffs.md
            #     - tracing.md
            #     - context.md
            #     - guardrails.md
            #     - multi_agent.md
            #     - Models:
            #         - models/index.md
            #         - models/litellm.md
            #     - config.md
            #     - visualization.md
            #     - Voice agents:
            #         - voice/quickstart.md
            #         - voice/pipeline.md
            #         - voice/tracing.md
            # - API Reference:
            #     - Agents:
            #         - ref/index.md
            #         - ref/agent.md
            #         - ref/run.md
            #         - ref/tool.md
            #         - ref/result.md
            #         - ref/stream_events.md
            #         - ref/handoffs.md
            #         - ref/lifecycle.md
            #         - ref/items.md
            #         - ref/run_context.md
            #         - ref/usage.md
            #         - ref/exceptions.md
            #         - ref/guardrail.md
            #         - ref/model_settings.md
            #         - ref/agent_output.md
            #         - ref/function_schema.md
            #         - ref/models/interface.md
            #         - ref/models/openai_chatcompletions.md
            #         - ref/models/openai_responses.md
            #         - ref/mcp/server.md
            #         - ref/mcp/util.md
            #     - Tracing:
            #         - ref/tracing/index.md
            #         - ref/tracing/create.md
            #         - ref/tracing/traces.md
            #         - ref/tracing/spans.md
            #         - ref/tracing/processor_interface.md
            #         - ref/tracing/processors.md
            #         - ref/tracing/scope.md
            #         - ref/tracing/setup.md
            #         - ref/tracing/span_data.md
            #         - ref/tracing/util.md
            #     - Voice:
            #         - ref/voice/pipeline.md
            #         - ref/voice/workflow.md
            #         - ref/voice/input.md
            #         - ref/voice/result.md
            #         - ref/voice/pipeline_config.md
            #         - ref/voice/events.md
            #         - ref/voice/exceptions.md
            #         - ref/voice/model.md
            #         - ref/voice/utils.md
            #         - ref/voice/models/openai_provider.md
            #         - ref/voice/models/openai_stt.md
            #         - ref/voice/models/openai_tts.md
            #     - Extensions:
            #         - ref/extensions/handoff_filters.md
            #         - ref/extensions/handoff_prompt.md
            #         - ref/extensions/litellm.md

extra:
  generator: false
  language: en
  alternate:
    - name: English
      link: /
      lang: en

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: mermaid
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn

extra_css:
  - stylesheets/extra.css

watch:
  - "src/agents" 